### ISSUE TITLE
Multiple errors on running

### ISSUE THREAD

**Issue by Probabilities** [BanjoByTheBay/BanjoBotAssets#48]
fail: BanjoBotAssets.CachingFNCentralMappingsProvider[0] Uncaught exception while reloading mappings from FNCentral System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at System.Collections.Generic.List`1.get_Item(Int32 index)    at CUE4Parse.MappingsProvider.Usmap.UsmapProperties.ParsePropertyInfo(FUsmapReader Ar, IReadOnlyList`1 nameLut) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapProperties.cs:line 34    at CUE4Parse.MappingsProvider.Usmap.UsmapProperties.ParseStruct(TypeMappings context, FUsmapReader Ar, IReadOnlyList`1 nameLut) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapProperties.cs:line 18    at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(FArchive archive) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 122    at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(Byte[] data, String name) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 25    at CUE4Parse.MappingsProvider.UsmapTypeMappingsProvider.Load(Byte[] bytes) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\UsmapTypeMappingsProvider.cs:line 17    at BanjoBotAssets.CachingFNCentralMappingsProvider.<>c__DisplayClass9_0.<<ReloadAsync>g__LoadCachedMappings|0>d.MoveNext() in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\CachingFNCentralMappingsProvider.cs:line 95 --- End of stack trace from previous location ---    at BanjoBotAssets.CachingFNCentralMappingsProvider.ReloadAsync() in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\CachingFNCentralMappingsProvider.cs:line 109
warn: BanjoBotAssets.AssetExportService[0] Retrying mappings
fail: BanjoBotAssets.CachingFNCentralMappingsProvider[0] Uncaught exception while reloading mappings from FNCentral System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at System.Collections.Generic.List`1.get_Item(Int32 index)    at CUE4Parse.MappingsProvider.Usmap.UsmapProperties.ParsePropertyInfo(FUsmapReader Ar, IReadOnlyList`1 nameLut) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapProperties.cs:line 34    at CUE4Parse.MappingsProvider.Usmap.UsmapProperties.ParseStruct(TypeMappings context, FUsmapReader Ar, IReadOnlyList`1 nameLut) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapProperties.cs:line 18    at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(FArchive archive) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 122    at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(Byte[] data, String name) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 25    at CUE4Parse.MappingsProvider.UsmapTypeMappingsProvider.Load(Byte[] bytes) in C:\Users\admin\Downloads\BanjoBotAssets\external\CUE4Parse\CUE4Parse\MappingsProvider\UsmapTypeMappingsProvider.cs:line 17    at BanjoBotAssets.CachingFNCentralMappingsProvider.<>c__DisplayClass9_0.<<ReloadAsync>g__LoadCachedMappings|0>d.MoveNext() in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\CachingFNCentralMappingsProvider.cs:line 95 --- End of stack trace from previous location ---    at BanjoBotAssets.CachingFNCentralMappingsProvider.ReloadAsync() in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\CachingFNCentralMappingsProvider.cs:line 109
fail: Microsoft.Extensions.Hosting.Internal.Host[9] BackgroundService failed BanjoBotAssets.AssetExportService+CriticalFailureException: Couldn't load mappings.    at BanjoBotAssets.AssetExportService.LoadMappingsAsync(CancellationToken cancellationToken) in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\AssetExportService.cs:line 227    at BanjoBotAssets.AssetExportService.RunAsync(CancellationToken cancellationToken) in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\AssetExportService.cs:line 128    at BanjoBotAssets.AssetExportService.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\AssetExportService.cs:line 81    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted. BanjoBotAssets.AssetExportService+CriticalFailureException: Couldn't load mappings.    at BanjoBotAssets.AssetExportService.LoadMappingsAsync(CancellationToken cancellationToken) in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\AssetExportService.cs:line 227    at BanjoBotAssets.AssetExportService.RunAsync(CancellationToken cancellationToken) in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\AssetExportService.cs:line 128    at BanjoBotAssets.AssetExportService.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\admin\Downloads\BanjoBotAssets\BanjoBotAssets\AssetExportService.cs:line 81    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)

**Comment by taradinoc** [comment]
This is now fixed.
